### ISSUE TITLE
permissions problem

### ISSUE THREAD

**Issue by vdubya** [OpenDBO/OpenRFA#14]
Unable to see the php you used to implement the MD include...or I'm doing something wrong.

![image](https://user-images.githubusercontent.com/6257997/44163296-d8950f80-a077-11e8-9ab4-ba22c2db45b8.png)

**Comment by jmerlan** [comment]
In order to get the MD to work, I had to allow the use PHP code. I went ahead and changed all users who have the "administrator" role on Drupal to be allowed to use PHP code. Just bare that in mind when giving any users admin rights. 

Note that there is a separate "shared parameter admin" role which is more restricted.

This should be fixed on your end.

**Comment by vdubya** [comment]
Confirmed working. I think we need to restrict admin to you and I, and focus on providing role-based permissions like `moderator`.
